Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 68

Metrics/ClassLength:
  Max: 258
  Exclude:
    - 'app/components/consumer/factories/persist_leasing_request.rb'

Metrics/ModuleLength:
  Max: 212

Metrics/ParameterLists:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - spec/**/*

Style/CaseEquality:
  Exclude:
    - spec/**/*

Style/SafeNavigation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/AbcSize:
  Max: 99
  Exclude:
    - spec/**/*

Metrics/CyclomaticComplexity:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 14

Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['(\A|\s)#']

Layout/MultilineHashBraceLayout:
  EnforcedStyle: symmetrical

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/AmbiguousOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7.0
  CacheRootDirectory: tmp/test-results
  Exclude:
    - bin/**
